version: '3.8'

services:
  db:
    image: postgres:16-alpine # Usar uma imagem Alpine é mais leve
    container_name: financas-db
    environment:
      POSTGRES_DB: financas_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: cto14porta7
    ports:
      - "15432:5432" # Mapeia a porta 5432 do container para a porta 5432 da sua máquina
    volumes:
      - db_data:/var/lib/postgresql/data # Volume persistente para os dados do banco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d financas_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: